### ISSUE TITLE
Anything about async methods?

### ISSUE THREAD

**Issue by benjamingr** [prepare/CsQuery#2]
This seems well maintained - do you plan to:

1) Publish to NuGet
2) make a better async API with async/await?

Also, since you're doing a lot of work on it - have you considered asking jamie for collaborator status on the original?

**Comment by prepare** [comment]
1. NuGet : I don't have that plan in near future  
2. async/await : Yes It's in the plan
3. asking jamie for collaborator :  ...
   My fork is in  study/ analysis phase,  
   so there are many bugs because I try to
   separate them into smaller modules ( eg. Dom, DomBuilder etc)
   so I'm afraid that  its too early to collab with the original one.

Thank you for your attention :)
